# Generated by Django 5.2 on 2026-03-05 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0013_alter_sales_date_of_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 9, 24, 8, 262736)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time_of_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 5, 9, 24, 8, 262142), null=True),
        ),
    ]
